### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by jesse-thomas** [yireo-training/magento2-example-custom-page-layout#1]
I'm looking for a way to add a widget to all 2 column left pages. 

Am I correct in my inderstanding that this module creates a new layout (based on 1 col), then a widget could be placed on any page using the custom layout? Or is there something here that can help me target all existing 2 column pages with a widget?

Thanks!

**Comment by jissereitsma** [comment]
No. All modules under this account `yireo-training` are purely meant for training purpose, not for usage on live sites. As I would see it, you simply would need to extend the 2 column left layout in your own theme or module, add a specific container with label to it and assign the widget to that container.

**Comment by jesse-thomas** [comment]
Good idea, thanks!
